db_name: cafis # Este projeto foi pensando para suportar MySql ou MariaDB
db_user: cafis # Usuário do banco com todas as permissões para a base de dados
db_pw: '_senha_do_banco_cafis@%123' # A senha do respectivo usuário do banco
django_secret_key: 'django-insecure-uz=3cijdv%q8_j(thvi089w=g5jklhhxa60!dyw0)c#-a4n(m*' # Insira sua django secret key
debug_mode: True # Use True para DEBUG or False para PRODUCTION
email_sistema: seu@email.com # E-mail utilizado para recuperação de senha
email_pw: su@senha123 # Senha do email acima
hCAPTCHA_Public_Key: 6484-dsadad4994ds949494d2314 # Inscreva-se https://www.hcaptcha.com/
hCAPTCHA_Secret_Key: 6484-dsadad4994ds949494d2314dsd4900c0952 # Cadastre seu site após se inscrever
GOOGLE_OAUTH2_PUBLIC_KEY: 74526484-dsadad4994ds949494d2314.apps.googleusercontent.com # Inscreva-se https://console.cloud.google.com/ e gere as chames para seu site
GOOGLE_OAUTH2_SECRET_KEY: GOCSPX-dsadad4994ds949494d2314
FACEBOOK_DEVELOPER_PUBLIC_KEY: 4994ds949494d2314 # Inscreva-se https://developers.facebook.com/ e gere as chaves para seu site
FACEBOOK_DEVELOPER_SECRET_KEY: 494d231479ff65cb6307b3