# Generated by Django 3.2.13 on 2022-06-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mural_de_noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('img', models.FileField(upload_to='imagens_mural', verbose_name='Imagem')),
                ('corpo', models.TextField()),
            ],
        ),
    ]
