# Generated by Django 3.2.13 on 2022-06-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mural_de_noticias',
            name='img',
            field=models.FileField(unique=True, upload_to='imagens_mural', verbose_name='Imagem'),
        ),
    ]
