# Generated by Django 3.2.13 on 2022-06-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_alter_mural_de_noticias_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representantes_Atuais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome compelto')),
                ('nome_apresentacao', models.CharField(max_length=50, verbose_name='Nome a ser exibido')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo ocupado')),
                ('img', models.FileField(unique=True, upload_to='imagens_representantes', verbose_name='Foto')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Dt. Inclusão')),
            ],
        ),
        migrations.AddField(
            model_name='mural_de_noticias',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Dt. Inclusão'),
        ),
    ]
