# Generated by Django 3.2.13 on 2022-06-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_artigos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigos',
            name='destaque',
        ),
        migrations.AddField(
            model_name='artigos',
            name='img',
            field=models.FileField(default='', unique=True, upload_to='imagens_artigo', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
