# Generated by Django 3.2.13 on 2022-07-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_auto_20220630_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('+', 'Lançamento'), ('-', 'Retirada')], max_length=1)),
                ('valor', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=300)),
            ],
        ),
    ]
