# Generated by Django 3.2.13 on 2022-10-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_landpagesessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mural_de_noticias',
            name='categoria',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
