# Generated by Django 3.2.13 on 2022-10-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_mural_de_noticias_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mural_de_noticias',
            options={'ordering': ['dt_inclusao'], 'verbose_name': 'Mural de Notícia', 'verbose_name_plural': 'Mural de Notícias'},
        ),
        migrations.AlterModelOptions(
            name='representantes_atuais',
            options={'ordering': ['dt_inclusao'], 'verbose_name': 'Representante do Cafís', 'verbose_name_plural': 'Representantes do Cafís'},
        ),
        migrations.AddField(
            model_name='representantes_atuais',
            name='atual',
            field=models.BooleanField(default=True),
        ),
    ]
