# Generated by Django 3.2.13 on 2022-10-12 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_auto_20221012_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigos',
            options={'ordering': ['dt_inclusao'], 'verbose_name': 'Artigo', 'verbose_name_plural': 'Artigos'},
        ),
        migrations.AlterModelOptions(
            name='landpagesessions',
            options={'ordering': ['id'], 'verbose_name': 'Configurações da página', 'verbose_name_plural': 'Configurações da página'},
        ),
        migrations.AlterModelOptions(
            name='mural_de_noticias',
            options={'ordering': ['dt_inclusao'], 'verbose_name': 'Mural de notícia', 'verbose_name_plural': 'Mural de notícias'},
        ),
        migrations.AlterModelOptions(
            name='transparencia',
            options={'ordering': ['dt_inclusao'], 'verbose_name': 'Representante', 'verbose_name_plural': 'Representantes'},
        ),
        migrations.AddField(
            model_name='transparencia',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Dt. Inclusão'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='representantes_atuais',
            name='atual',
            field=models.BooleanField(default=True, verbose_name='Representante atual'),
        ),
    ]
