# Generated by Django 3.2.13 on 2022-10-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0010_auto_20221012_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoriaHorarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_e_horario', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='transparencia',
            options={'ordering': ['dt_inclusao'], 'verbose_name': 'Transparência do Cafís', 'verbose_name_plural': 'Transparência do Cafís'},
        ),
        migrations.AlterField(
            model_name='representantes_atuais',
            name='atual',
            field=models.BooleanField(default=True, verbose_name='representante atual'),
        ),
        migrations.CreateModel(
            name='Monitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('monitor', models.CharField(max_length=100)),
                ('horarios', models.ManyToManyField(blank=True, to='landingpage.MonitoriaHorarios')),
            ],
            options={
                'verbose_name': 'Monitoria',
                'verbose_name_plural': 'Monitorias',
                'ordering': ['id'],
            },
        ),
    ]
