# Generated by Django 3.2.17 on 2023-06-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0011_auto_20221012_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_sliede', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='slides')),
            ],
        ),
        migrations.AlterModelOptions(
            name='monitoriahorarios',
            options={'ordering': ['id'], 'verbose_name': 'Horário de Monitoria', 'verbose_name_plural': 'Horários de Monitorias'},
        ),
    ]
